export const alerts = [
  {
    id: 'soldout-1',
    type: 'warning',
    title: 'VIP seats filling fast',
    message: 'The VIP section for Neon Nights is almost sold out. Book soon to reserve premium seating.',
  },
  {
    id: 'new-show',
    type: 'info',
    title: 'New show added',
    message: 'A second evening performance for Jazz by Moonlight has been added at Crescent Hall.',
  },
  {
    id: 'lineup-1',
    type: 'danger',
    title: 'Lineup change',
    message: 'The Saturday set for Theatre Odyssey will now start 30 minutes earlier than originally published.',
  },
  {
    id: 'capacity-1',
    type: 'warning',
    title: 'Limited seating',
    message: 'Only a few balcony seats remain for Bolly Night Show at Riverfront Pavilion.',
  },
];

export const events = [
  {
    id: 'neon-nights',
    title: 'Neon Nights',
    artist: 'Sunset Collective',
    genre: 'Concert / Electronic',
    tags: ['concert', 'festival'],
    poster: '🎧',
    coverImage: 'https://images.unsplash.com/photo-1521321870013-183f3d452e0d?auto=format&fit=crop&w=900&q=80',
    city: 'Karachi',
    venueName: 'Seaview Arena',
    date: 'Fri 31 May',
    description: 'An immersive electronic music night with lasers, live visuals, and headline DJs.',
    sessions: [
      { id: 'nn-830', time: '8:30 PM', date: 'Fri 31 May', price: 1200, label: 'VIP', zone: 'A' },
      { id: 'nn-1130', time: '11:30 PM', date: 'Fri 31 May', price: 900, label: 'Standard', zone: 'B' },
    ],
  },
  {
    id: 'theatre-odyssey',
    title: 'Theatre Odyssey',
    artist: 'Lahore Stage Co.',
    genre: 'Theatre / Drama',
    tags: ['theatre', 'local'],
    poster: '🎭',
    coverImage: 'https://images.unsplash.com/photo-1512545348328-018e5abb8a61?auto=format&fit=crop&w=900&q=80',
    city: 'Lahore',
    venueName: 'Liberty Playhouse',
    date: 'Sat 1 Jun',
    description: 'A contemporary drama exploring city life, culture, and the stories that bring us together.',
    sessions: [
      { id: 'to-700', time: '7:00 PM', date: 'Sat 1 Jun', price: 850, label: 'Premium', zone: 'A' },
      { id: 'to-930', time: '9:30 PM', date: 'Sat 1 Jun', price: 650, label: 'Standard', zone: 'B' },
    ],
  },
  {
    id: 'jazz-moonlight',
    title: 'Jazz by Moonlight',
    artist: 'The Crescent Quartet',
    genre: 'Jazz / Live',
    tags: ['concert', 'jazz'],
    poster: '🎷',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=900&q=80',
    city: 'Karachi',
    venueName: 'Crescent Hall',
    date: 'Sun 2 Jun',
    description: 'An intimate jazz evening featuring classic standards and fresh new arrangements.',
    sessions: [
      { id: 'jm-830', time: '8:30 PM', date: 'Sun 2 Jun', price: 1100, label: 'Lounge', zone: 'A' },
      { id: 'jm-1030', time: '10:30 PM', date: 'Sun 2 Jun', price: 750, label: 'Balcony', zone: 'B' },
    ],
  },
  {
    id: 'urban-drumline',
    title: 'Urban Drumline',
    artist: 'Karachi Beat Crew',
    genre: 'Percussion / Street',
    tags: ['festival', 'local'],
    poster: '🥁',
    coverImage: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&w=900&q=80',
    city: 'Karachi',
    venueName: 'Harbour Stage',
    date: 'Sat 1 Jun',
    description: 'A high-energy street percussion party with live drummers, dancers, and interactive beats.',
    sessions: [
      { id: 'ud-730', time: '7:30 PM', date: 'Sat 1 Jun', price: 850, label: 'Front Row', zone: 'A' },
      { id: 'ud-930', time: '9:30 PM', date: 'Sat 1 Jun', price: 650, label: 'General', zone: 'B' },
    ],
  },
  {
    id: 'bolly-night',
    title: 'Bolly Night Show',
    artist: 'Lahore Stars',
    genre: 'Music / Dance',
    tags: ['concert', 'bollywood'],
    poster: '💃',
    coverImage: 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=80',
    city: 'Lahore',
    venueName: 'Riverfront Pavilion',
    date: 'Sun 2 Jun',
    description: 'A vibrant evening of Bollywood dance, live vocals, and multimedia stage production.',
    sessions: [
      { id: 'bn-800', time: '8:00 PM', date: 'Sun 2 Jun', price: 950, label: 'Premium', zone: 'A' },
      { id: 'bn-1030', time: '10:30 PM', date: 'Sun 2 Jun', price: 750, label: 'Standard', zone: 'B' },
    ],
  },
  {
    id: 'opera-moonrise',
    title: 'Opera Moonrise',
    artist: 'Karachi Opera Ensemble',
    genre: 'Opera / Classical',
    tags: ['theatre', 'classical'],
    poster: '🎼',
    coverImage: 'https://images.unsplash.com/photo-1511376777868-611b54f68947?auto=format&fit=crop&w=900&q=80',
    city: 'Karachi',
    venueName: 'Gallery Theatre',
    date: 'Mon 3 Jun',
    description: 'A dramatic opera performance with full orchestra, powerful vocals, and modern staging.',
    sessions: [
      { id: 'om-700', time: '7:00 PM', date: 'Mon 3 Jun', price: 1100, label: 'Orchestra', zone: 'A' },
      { id: 'om-930', time: '9:30 PM', date: 'Mon 3 Jun', price: 800, label: 'Gallery', zone: 'B' },
    ],
  },
];

export const upcomingEvents = [
  {
    id: 'street-fest',
    title: 'City Street Fest',
    artist: 'Multiple acts',
    genre: 'Festival / Street',
    tags: ['july', 'festival'],
    poster: '🌆',
    coverImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
    release: 'Opening July 2026',
  },
  {
    id: 'standup-saturday',
    title: 'Standup Saturday',
    artist: 'Local comedians',
    genre: 'Comedy / Live',
    tags: ['july', 'local'],
    poster: '😂',
    coverImage: 'https://images.unsplash.com/photo-1546787351-51cbc3b20d46?auto=format&fit=crop&w=900&q=80',
    release: 'Opening July 2026',
  },
  {
    id: 'folk-carnival',
    title: 'Folk Carnival',
    artist: 'Traditional Ensembles',
    genre: 'Folk / Cultural',
    tags: ['august', 'local'],
    poster: '🪕',
    coverImage: 'https://images.unsplash.com/photo-1517511620798-cec17d428bc0?auto=format&fit=crop&w=900&q=80',
    release: 'Opening August 2026',
  },
  {
    id: 'midnight-jam',
    title: 'Midnight Jam',
    artist: 'City Jazz Collective',
    genre: 'Jazz / Afterparty',
    tags: ['june', 'jazz'],
    poster: '🌙',
    coverImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=80',
    release: 'Opening June 2026',
  },
];

export const venues = [
  {
    id: 'seaview',
    name: 'Seaview Arena',
    city: 'Karachi',
    location: 'Seaview Boulevard',
    rating: 4.7,
    capacity: 2400,
    tags: ['open-air', 'vip', 'festival'],
    description: 'A large beachfront event space designed for concerts, festivals, and city celebrations.',
    amenities: ['Open Air', 'VIP Boxes', 'Food Trucks', 'Live Screens'],
  },
  {
    id: 'crescent',
    name: 'Crescent Hall',
    city: 'Karachi',
    location: 'Clifton',
    rating: 4.6,
    capacity: 900,
    tags: ['soundstage', 'premium'],
    description: 'A premium indoor hall for jazz, acoustic concerts, and curated performances.',
    amenities: ['Acoustic Sound', 'VIP Lounge', 'Climate Control', 'Cultural Events'],
  },
  {
    id: 'liberty',
    name: 'Liberty Playhouse',
    city: 'Lahore',
    location: 'Liberty Market',
    rating: 4.8,
    capacity: 600,
    tags: ['theatre', 'local'],
    description: 'A boutique theatre space supporting local drama, spoken word, and performance art.',
    amenities: ['Reserved Seating', 'Snack Bar', 'Accessible Entry', 'Art Installations'],
  },
  {
    id: 'harbour',
    name: 'Harbour Stage',
    city: 'Karachi',
    location: 'Portside Promenade',
    rating: 4.5,
    capacity: 1600,
    tags: ['open-air', 'street', 'live'],
    description: 'A waterfront stage for drumline performances, street acts, and evening concerts.',
    amenities: ['Waterfront Views', 'Food Stalls', 'Open Seating', 'Live DJs'],
  },
  {
    id: 'gallery',
    name: 'Gallery Theatre',
    city: 'Karachi',
    location: 'Art District',
    rating: 4.9,
    capacity: 520,
    tags: ['classical', 'premium', 'theatre'],
    description: 'An elegant black-box theatre hosting operas, classical concerts, and curated performances.',
    amenities: ['Orchestra Pit', 'Tiered Seating', 'Art Cafe', 'Air Conditioned'],
  },
  {
    id: 'riverfront',
    name: 'Riverfront Pavilion',
    city: 'Lahore',
    location: 'Riverside Road',
    rating: 4.7,
    capacity: 1200,
    tags: ['concert', 'bollywood', 'open-air'],
    coverImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
    description: 'A riverside pavilion perfect for concerts, Bollywood nights, and cultural showcases.',
    amenities: ['Riverside Dining', 'Lawn Seating', 'Live Screens', 'VIP Terrace'],
  },
];

export const seatLayout = {
  rows: 8,
  cols: 10,
  takenSeats: ['A1', 'A2', 'B5', 'C4', 'D8', 'E3', 'F2', 'G6', 'H10'],
  premiumRows: [0, 1],
};
